# Generated by Django 3.1.2 on 2020-11-10 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201104_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_list', to='recipes.recipe'),
        ),
    ]
